[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd bots/discord-bot && npm install"]

[phases.build]
cmds = ["cd bots/discord-bot && npm run build"]

[start]
cmd = "cd bots/discord-bot && node dist/index.js"
